# Generated by Django 6.0.5 on 2026-05-27 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=65)),
                ('street', models.CharField(max_length=128)),
                ('house_number', models.CharField(blank=True, max_length=16, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=19, null=True)),
                ('headline', models.CharField(max_length=100, verbose_name='Slogan / Titel')),
                ('description', models.TextField(verbose_name='Beschreibung (Über mich)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('country', 'city', 'street', 'headline', 'description'), name='unique_profile_with_description')],
            },
        ),
    ]
